version: '3.8'

services:
  zeppelin:
    image: myzeppelin
    build:
      context: .
    environment:
      # FLINK_HOME: /opt/flink
      SPARK_HOME: /opt/spark
      ZEPPELIN_LOG_DIR: /logs
      ZEPPELIN_NOTEBOOK_DIR: /notebook
    volumes:
      - ./logs:/logs
      - ./notebook:/notebook
      - ./spark-3.2.1-bin-hadoop3.2:/opt/spark
      # - /usr/lib/flink-1.12.2:/opt/flink
    ports:
      - 8080:8080
